-- Criar banco de dados (ajuste nome)
CREATE DATABASE IF NOT EXISTS qna_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE qna_db;


-- tabela users
CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
senha VARCHAR(255) NOT NULL,
bio TEXT DEFAULT NULL,
avatar VARCHAR(255) DEFAULT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;


CREATE TABLE questions (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
titulo VARCHAR(255) NOT NULL,
conteudo TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE answers (
id INT AUTO_INCREMENT PRIMARY KEY,
question_id INT NOT NULL,
user_id INT NOT NULL,
conteudo TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE comments (
id INT AUTO_INCREMENT PRIMARY KEY,
answer_id INT NOT NULL,
user_id INT NOT NULL,
conteudo TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (answer_id) REFERENCES answers(id) ON DELETE CASCADE,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;